"""
Generate companion notebooks for the existing xpress_vs_pulp comparison.

Creates three self-contained, educational notebooks:
  01_scoring_systems_impact.ipynb
  02_optimizer_constraints.ipynb
  03_projection_uncertainty.ipynb

Usage:
    uv run python scripts/generate_optimization_notebooks.py
"""

import nbformat as nbf
from pathlib import Path

OUT = Path(__file__).parent.parent / "notebooks"

MARKDOWN_TEMPLATES = {
    "setup": """\
## Setup

This notebook uses FFPy's optimizer and scoring modules. No database required —
we construct sample players in-memory.

```python
# Run this cell to install analysis deps (first time only)
# !uv sync --group analysis
```""",

    "colophon": """\
---
*Notebook generated by `scripts/generate_optimization_notebooks.py`.*
""",
}


def md(src: str) -> dict:
    return nbf.v4.new_markdown_cell(src)


def code(src: str) -> dict:
    return nbf.v4.new_code_cell(src)


# ── Shared sample data (used across notebooks) ──────────────────────────────

SAMPLE_PLAYER_STATS = """\
# ── Sample players with detailed stat projections ──────────────────────
# Each dict: positional stats that ScoringConfig.calculate_fantasy_points reads.
sample_stats = [
    # ── QBs ──
    {"name": "Josh Allen",      "position": "QB", "team": "BUF",
     "passing_yards": 285, "passing_tds": 2.4, "interceptions": 0.7,
     "rushing_yards": 45,  "rushing_tds": 0.5,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
    {"name": "Patrick Mahomes", "position": "QB", "team": "KC",
     "passing_yards": 310, "passing_tds": 2.8, "interceptions": 0.6,
     "rushing_yards": 20,  "rushing_tds": 0.2,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
    {"name": "Lamar Jackson",   "position": "QB", "team": "BAL",
     "passing_yards": 235, "passing_tds": 1.8, "interceptions": 0.8,
     "rushing_yards": 70,  "rushing_tds": 0.6,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
    {"name": "Jalen Hurts",     "position": "QB", "team": "PHI",
     "passing_yards": 225, "passing_tds": 1.7, "interceptions": 0.6,
     "rushing_yards": 55,  "rushing_tds": 0.7,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
    {"name": "Joe Burrow",      "position": "QB", "team": "CIN",
     "passing_yards": 290, "passing_tds": 2.5, "interceptions": 0.9,
     "rushing_yards": 10,  "rushing_tds": 0.1,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
    # ── RBs ──
    {"name": "Christian McCaffrey", "position": "RB", "team": "SF",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 85, "rushing_tds": 0.8,
     "receiving_yards": 45, "receptions": 4.5, "receiving_tds": 0.2},
    {"name": "Bijan Robinson",  "position": "RB", "team": "ATL",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 75, "rushing_tds": 0.6,
     "receiving_yards": 35, "receptions": 3.0, "receiving_tds": 0.1},
    {"name": "Saquon Barkley",  "position": "RB", "team": "PHI",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 80, "rushing_tds": 0.7,
     "receiving_yards": 30, "receptions": 2.5, "receiving_tds": 0.1},
    {"name": "Austin Ekeler",   "position": "RB", "team": "WAS",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 55, "rushing_tds": 0.4,
     "receiving_yards": 50, "receptions": 4.0, "receiving_tds": 0.2},
    {"name": "James Cook",      "position": "RB", "team": "BUF",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 65, "rushing_tds": 0.5,
     "receiving_yards": 20, "receptions": 2.0, "receiving_tds": 0.1},
    # ── WRs ──
    {"name": "Tyreek Hill",     "position": "WR", "team": "MIA",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 5,  "rushing_tds": 0.0,
     "receiving_yards": 95, "receptions": 6.5, "receiving_tds": 0.8},
    {"name": "CeeDee Lamb",     "position": "WR", "team": "DAL",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 5,  "rushing_tds": 0.0,
     "receiving_yards": 90, "receptions": 6.0, "receiving_tds": 0.6},
    {"name": "Justin Jefferson","position": "WR", "team": "MIN",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 85, "receptions": 5.5, "receiving_tds": 0.5},
    {"name": "Amon-Ra St. Brown","position": "WR", "team": "DET",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 80, "receptions": 6.0, "receiving_tds": 0.5},
    {"name": "Stefon Diggs",    "position": "WR", "team": "HOU",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 70, "receptions": 5.0, "receiving_tds": 0.4},
    # ── TEs ──
    {"name": "Travis Kelce",    "position": "TE", "team": "KC",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 65, "receptions": 4.5, "receiving_tds": 0.5},
    {"name": "Mark Andrews",    "position": "TE", "team": "BAL",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 55, "receptions": 4.0, "receiving_tds": 0.4},
    {"name": "George Kittle",   "position": "TE", "team": "SF",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 60, "receptions": 3.5, "receiving_tds": 0.3},
    # ── K ──
    {"name": "Justin Tucker",   "position": "K", "team": "BAL",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
    # ── DST ──
    {"name": "49ers DST",       "position": "DST", "team": "SF",
     "passing_yards": 0, "passing_tds": 0, "interceptions": 0,
     "rushing_yards": 0,  "rushing_tds": 0.0,
     "receiving_yards": 0,  "receptions": 0, "receiving_tds": 0},
]"""


NB_METADATA = {
    "kernelspec": {
        "display_name": "Python (FFPy)",
        "language": "python",
        "name": "ffpy",
    },
    "language_info": {
        "codemirror_mode": {"name": "ipython", "version": 3},
        "file_extension": ".py",
        "mimetype": "text/x-python",
        "name": "python",
        "nbconvert_exporter": "python",
        "pygments_lexer": "ipython3",
        "version": "3.13",
    },
}


# =============================================================================
# NOTEBOOK 1 – Scoring System Impact
# =============================================================================

def build_notebook_01() -> nbf.NotebookNode:
    cells = []

    cells.append(md("""\
# 01 — Scoring System Impact on Lineup Optimization

**What you'll learn:**
- How the four built-in scoring systems (Standard, Half-PPR, PPR, custom) change
  each player's fantasy point value
- Which positions gain or lose value when receptions are rewarded
- How the optimizer's optimal lineup shifts across scoring systems
- How to define a custom scoring rule and see its effect

**Prerequisites:** FFPy installed (`uv sync`). No database needed."""))
    cells.append(md(MARKDOWN_TEMPLATES["setup"]))

    cells.append(md("## Imports"))
    cells.append(code("""\
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure ffpy is importable (works from notebooks/ dir)
_repo = Path.cwd()
while not (_repo / "pyproject.toml").exists() and _repo.parent != _repo:
    _repo = _repo.parent
sys.path.insert(0, str(_repo / "src"))

from ffpy.optimizer import LineupOptimizer, Player, RosterConstraints
from ffpy.scoring import ScoringConfig, calculate_fantasy_points

sns.set_theme(style="whitegrid")
plt.rcParams["figure.dpi"] = 120
"""))

    cells.append(md("## Data: Sample Player Stats"))
    cells.append(code(SAMPLE_PLAYER_STATS))

    cells.append(md("""\
### 1. Define the Scoring Systems

FFPy ships with four presets. Let's list their key difference —
the `reception_points` field:"""))
    cells.append(code("""\
# Create the four scoring systems
systems = {
    "Standard": ScoringConfig.standard(),
    "Half-PPR": ScoringConfig.half_ppr(),
    "PPR":      ScoringConfig.ppr(),
}

# Show the one parameter that changes
rows = []
for name, cfg in systems.items():
    rows.append({"System": name, "Reception Points": cfg.reception_points})
pd.DataFrame(rows)
"""))

    cells.append(md("""\
### 2. Compute Fantasy Points Per Player Per System

We use `calculate_fantasy_points(stats, config)` for every player × system pair."""))
    cells.append(code("""\
points_table = []
for p in sample_stats:
    for sys_name, config in systems.items():
        pts = calculate_fantasy_points(p, config)
        points_table.append({
            "player": p["name"],
            "position": p["position"],
            "team": p["team"],
            "system": sys_name,
            "fantasy_points": round(pts, 1),
        })

df_pts = pd.DataFrame(points_table)
df_pts.head(12)
"""))

    cells.append(md("### 3. Visualise: Who Gains from PPR?"))
    cells.append(code("""\
# Pivot: one row per player, columns per system
pivot = df_pts.pivot_table(
    index=["player", "position", "team"],
    columns="system",
    values="fantasy_points",
).reset_index()

# Sort by PPR (highest first)
pivot = pivot.sort_values("PPR", ascending=False)

# Delta column
pivot["PPR_Bonus"] = pivot["PPR"] - pivot["Standard"]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left: side-by-side bars for top 10 PPR scorers
top10 = pivot.head(10)
x = range(len(top10))
w = 0.25
for i, sys_name in enumerate(["Standard", "Half-PPR", "PPR"]):
    axes[0].bar(
        [xi + i * w for xi in x],
        top10[sys_name],
        width=w,
        label=sys_name,
    )
axes[0].set_xticks([xi + w for xi in x])
axes[0].set_xticklabels(top10["player"], rotation=45, ha="right")
axes[0].set_ylabel("Fantasy Points")
axes[0].set_title("Top 10 Players Across Scoring Systems")
axes[0].legend()

# Right: PPR bonus by position
# Spread the jitter for visibility
rng = np.random.default_rng(42)
for pos, color in [("QB", "#1f77b4"), ("RB", "#ff7f0e"), ("WR", "#2ca02c"), ("TE", "#d62728")]:
    subset = pivot[pivot["position"] == pos]
    axes[1].scatter(
        [pos] * len(subset) + rng.uniform(-0.15, 0.15, len(subset)),
        subset["PPR_Bonus"],
        color=color,
        alpha=0.7,
        s=60,
    )

axes[1].axhline(0, color="grey", linestyle="--", linewidth=0.8)
axes[1].set_ylabel("PPR Bonus (PPR − Standard)")
axes[1].set_title("Which Positions Gain from PPR?")

plt.tight_layout()
plt.show()
"""))

    cells.append(md("""\
**Observation:** WRs and pass-catching RBs see the largest PPR bonus because
volume receptions directly add points. QBs are almost untouched (they rarely
receive passes). TEs with high target volume also get a nice boost.
"""))

    cells.append(md("### 4. Optimise a Lineup Under Each Scoring System"))
    cells.append(code("""\
def build_players(stats_list, config):
    \"\"\"Convert stat dicts → Player objects with system-appropriate projected_points.\"\"\"
    players = []
    for s in stats_list:
        pts = calculate_fantasy_points(s, config)
        players.append(Player(
            name=s["name"],
            position=s["position"],
            team=s["team"],
            projected_points=pts,
        ))
    return players

constraints = RosterConstraints.standard()

results = {}
for sys_name, config in systems.items():
    pool = build_players(sample_stats, config)
    opt = LineupOptimizer(constraints)
    res = opt.optimize(pool)
    results[sys_name] = res

# Display side-by-side
print(f"{'System':<12} {'Total':>6} {'Starters':>9} {'Top Bench':>25}")
print("-" * 55)
for sys_name, res in results.items():
    top = res.bench[0].name if res.bench else "—"
    print(f"{sys_name:<12} {res.total_points:>6.1f} {len(res.starters):>4}  "
          f"{'':>5} {top:<25}")
"""))

    cells.append(md("### 5. Compare the Actual Lineups"))
    cells.append(code("""\
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for idx, (sys_name, config) in enumerate(systems.items()):
    res = results[sys_name]
    by_pos = res.get_starters_by_position()
    ax = axes[idx]

    y = 0
    for pos in ["QB", "RB", "WR", "TE", "K", "DST"]:
        for pl in by_pos.get(pos, []):
            ax.barh(y, pl.projected_points, height=0.6, label=pos if y == 0 else "")
            ax.text(pl.projected_points + 0.3, y, pl.name, va="center", fontsize=8)
            y += 1

    ax.set_yticks([])
    ax.set_xlabel("Projected Points")
    ax.set_title(f"{sys_name} — {res.total_points:.1f} total")
    if idx == 0:
        ax.legend(loc="lower right")

plt.tight_layout()
plt.show()
"""))

    cells.append(md("""\
### 6. Try a Custom Scoring Rule

What if your league rewards big plays? Let's create a **Big-Play Bonus** system
that adds +1 point for 40+ yard TDs. The `ScoringConfig` supports a
`bonus_settings` dict for this:"""))
    cells.append(code("""\
big_play = ScoringConfig(
    name="Big Play Bonus",
    reception_points=0.5,  # Half-PPR base
    bonus_settings={"passing_td_40_plus": 1.0, "rushing_td_40_plus": 1.0},
)

# For simplicity, we'll approximate the bonus by assuming a fraction of TDs
# are "long". In a real app the projections would include this flag.
import copy
custom_stats = copy.deepcopy(sample_stats)
for p in custom_stats:
    # Assume 20% of TDs are 40+ yard plays
    long_tds = p.get("passing_tds", 0) * 0.2 + p.get("rushing_tds", 0) * 0.2 \
               + p.get("receiving_tds", 0) * 0.2
    bonus = long_tds * 1.0  # +1 per big-play TD
    p["bonus"] = round(bonus, 1)

# Recalculate with bonus baked into projected_points
pool_big = []
for s in custom_stats:
    base = calculate_fantasy_points(s, big_play)
    pool_big.append(Player(
        name=s["name"],
        position=s["position"],
        team=s["team"],
        projected_points=round(base + s.get("bonus", 0), 1),
    ))

opt_big = LineupOptimizer(RosterConstraints.standard())
res_big = opt_big.optimize(pool_big)

print("=== Big-Play Bonus League ===")
print(opt_big.analyze_lineup(res_big))
"""))

    cells.append(md("""\
### Key Takeaways

1. **Scoring rules directly change player rankings** — a PPR league values
   pass-catching RBs and slot WRs more than a Standard league.
2. **The optimizer responds to those changes** — the optimal lineup shifts when
   reception_points changes.
3. **Custom bonuses are easy to model** — any rule that can be expressed as a
   per-player stat adjustment integrates cleanly with the optimizer.
4. **For learning:** always check which scoring system your league uses before
   trusting an optimizer's output. Run it with your league's exact config.
"""))

    cells.append(md(MARKDOWN_TEMPLATES["colophon"]))

    nb = nbf.v4.new_notebook(metadata=NB_METADATA)
    nb.cells = cells
    return nb


# =============================================================================
# NOTEBOOK 2 – Optimizer Constraints Deep Dive
# =============================================================================

def build_notebook_02() -> nbf.NotebookNode:
    cells = []

    cells.append(md("""\
# 02 — Optimizer Constraints Deep Dive

**What you'll learn:**
- How every constraint type in `RosterConstraints` shapes the optimal lineup
- Compare Standard vs Superflex vs No-Kicker/DST formats
- How player locks (forced starts/sits) affect total projected points
- How team stack limits force lineup diversification
- How salary caps create knapsack-style trade-offs
- How to combine multiple constraints for league-specific rules

**Prerequisites:** FFPy installed, `matplotlib`, `seaborn`. No database needed."""))
    cells.append(md(MARKDOWN_TEMPLATES["setup"]))

    cells.append(md("## Imports"))
    cells.append(code("""\
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

_repo = Path.cwd()
while not (_repo / "pyproject.toml").exists() and _repo.parent != _repo:
    _repo = _repo.parent
sys.path.insert(0, str(_repo / "src"))

from ffpy.optimizer import (
    LineupOptimizer, LineupResult,
    Player, PlayerStatus, RosterConstraints,
)

sns.set_theme(style="whitegrid")
plt.rcParams["figure.dpi"] = 120
"""))

    cells.append(md("## Data: a Larger Player Pool"))
    cells.append(code("""\
def make_pool():
    \"\"\"Return 30+ players across all positions with realistic projections.\"\"\"
    # ── QB (6) ──
    qbs = [
        Player("Josh Allen", "QB", "BUF", 25.8, opponent="MIA"),
        Player("Patrick Mahomes", "QB", "KC", 24.5, opponent="DEN"),
        Player("Lamar Jackson", "QB", "BAL", 24.2, opponent="CLE"),
        Player("Jalen Hurts", "QB", "PHI", 23.1, opponent="NYG"),
        Player("Joe Burrow", "QB", "CIN", 22.0, opponent="PIT"),
        Player("Dak Prescott", "QB", "DAL", 21.5, opponent="WAS"),
    ]
    # ── RB (8) ──
    rbs = [
        Player("Christian McCaffrey", "RB", "SF", 22.4, opponent="ARI"),
        Player("Saquon Barkley", "RB", "PHI", 20.1, opponent="NYG"),
        Player("Bijan Robinson", "RB", "ATL", 19.2, opponent="NO"),
        Player("Austin Ekeler", "RB", "WAS", 18.7, opponent="DAL"),
        Player("James Cook", "RB", "BUF", 15.2, opponent="MIA"),
        Player("Derrick Henry", "RB", "BAL", 17.5, opponent="CLE"),
        Player("Isiah Pacheco", "RB", "KC", 13.8, opponent="DEN"),
        Player("Raheem Mostert", "RB", "MIA", 14.2, opponent="BUF"),
    ]
    # ── WR (8) ──
    wrs = [
        Player("Tyreek Hill", "WR", "MIA", 19.8, opponent="BUF"),
        Player("CeeDee Lamb", "WR", "DAL", 18.5, opponent="WAS"),
        Player("Justin Jefferson", "WR", "MIN", 18.2, opponent="CHI"),
        Player("Amon-Ra St. Brown", "WR", "DET", 16.9, opponent="MIN"),
        Player("Stefon Diggs", "WR", "HOU", 14.3, opponent="IND"),
        Player("Davante Adams", "WR", "LV", 14.8, opponent="LAC"),
        Player("Deebo Samuel", "WR", "SF", 15.5, opponent="ARI"),
        Player("Garrett Wilson", "WR", "NYJ", 13.2, opponent="NE"),
    ]
    # ── TE (4) ──
    tes = [
        Player("Travis Kelce", "TE", "KC", 16.5, opponent="DEN"),
        Player("Mark Andrews", "TE", "BAL", 14.2, opponent="CLE"),
        Player("George Kittle", "TE", "SF", 13.1, opponent="ARI"),
        Player("Sam LaPorta", "TE", "DET", 12.5, opponent="MIN"),
    ]
    # ── K (4) ──
    ks = [
        Player("Justin Tucker", "K", "BAL", 9.5, opponent="CLE"),
        Player("Harrison Butker", "K", "KC", 9.2, opponent="DEN"),
        Player("Brandon Aubrey", "K", "DAL", 8.8, opponent="WAS"),
        Player("Jake Moody", "K", "SF", 8.5, opponent="ARI"),
    ]
    # ── DST (4) ──
    dsts = [
        Player("49ers DST", "DST", "SF", 10.2, opponent="ARI"),
        Player("Ravens DST", "DST", "BAL", 9.5, opponent="CLE"),
        Player("Cowboys DST", "DST", "DAL", 8.8, opponent="WAS"),
        Player("Chiefs DST", "DST", "KC", 8.5, opponent="DEN"),
    ]
    return qbs + rbs + wrs + tes + ks + dsts

pool = make_pool()
print(f"Player pool: {len(pool)}")
df_pool = pd.DataFrame([
    {"name": p.name, "pos": p.position, "team": p.team, "proj": p.projected_points}
    for p in pool
])
df_pool.groupby("pos").agg(count=("name", "count"), avg_proj=("proj", "mean"))
"""))

    cells.append(md("""\
### 1. Roster Format Comparison

The three built-in roster formats differ in which positions are required
and how FLEX works:"""))
    cells.append(code("""\
formats = {
    "Standard":     RosterConstraints.standard(),
    "No K/DST":     RosterConstraints.no_kicker_dst(),
    "Superflex":    RosterConstraints.superflex(),
}

for name, c in formats.items():
    print(f"{name:>12}  {c}")
"""))

    cells.append(code("""\
results_fmt = {}
for fmt_name, constraints in formats.items():
    opt = LineupOptimizer(constraints)
    res = opt.optimize(pool)
    results_fmt[fmt_name] = res

# Summary table
rows = []
for fmt_name, res in results_fmt.items():
    rows.append({
        "Format": fmt_name,
        "Starters": len(res.starters),
        "Total Pts": round(res.total_points, 1),
        "Avg/Starter": round(res.total_points / len(res.starters), 1),
        "Solve (ms)": round(res.solve_time_ms, 1),
    })
print("=== Format Comparison ===")
pd.DataFrame(rows).to_string(index=False)

# Visual comparison
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
for idx, (fmt_name, res) in enumerate(results_fmt.items()):
    by_pos = res.get_starters_by_position()
    ax = axes[idx]
    y = 0
    for pos in ["QB", "RB", "WR", "TE", "FLEX", "K", "DST"]:
        for pl in by_pos.get(pos, []):
            ax.barh(y, pl.projected_points, height=0.7)
            ax.text(pl.projected_points + 0.3, y, pl.name, va="center", fontsize=8)
            y += 1
    ax.set_yticks([])
    ax.set_xlabel("Projected Points")
    ax.set_title(f"{fmt_name} — {res.total_points:.1f} pts")
plt.tight_layout()
plt.show()
"""))

    cells.append(md("""\
**Key observations:**
- **No K/DST** frees up two roster spots, typically adding an extra WR or RB
- **Superflex** allows a second QB, which often boosts total points since QBs
  have the highest raw projections
- Solve times are trivial (<50ms) at this problem size
"""))

    cells.append(md("""\
### 2. Player Locks (Forced Starts / Sits)

What happens when you must start or bench a specific player?"""))
    cells.append(code("""\
# Baseline: standard format, no locks
opt_free = LineupOptimizer(RosterConstraints.standard())
free_res = opt_free.optimize(pool)

# Constraint: force-start Josh Allen, force-sit Christian McCaffrey
locked = RosterConstraints.standard()
locked.locked_in = {"Josh Allen"}
locked.locked_out = {"Christian McCaffrey"}

opt_locked = LineupOptimizer(locked)
locked_res = opt_locked.optimize(pool)

print("=== Free Optimization ===")
print(opt_free.analyze_lineup(free_res))
print()

print("=== Josh Allen forced START, CMC forced SIT ===")
print(opt_locked.analyze_lineup(locked_res))
print(f"\\nCost of locks: {free_res.total_points - locked_res.total_points:.1f} pts")
"""))

    cells.append(md("""\
### 3. Injury Status Handling

Players with `INJURED`, `OUT`, `BYE`, or `LOCKED` status are excluded.
`QUESTIONABLE` players are still eligible."""))
    cells.append(code("""\
injured_pool = make_pool()
# Simulate some injuries
injured_pool[0]  = Player("Josh Allen", "QB", "BUF", 25.8, status=PlayerStatus.INJURED)
injured_pool[3]  = Player("Jalen Hurts", "QB", "PHI", 23.1, status=PlayerStatus.OUT)
injured_pool[14] = Player("Stefon Diggs", "WR", "HOU", 14.3, status=PlayerStatus.QUESTIONABLE)
injured_pool[20] = Player("Travis Kelce", "TE", "KC", 16.5, status=PlayerStatus.BYE)

opt_inj = LineupOptimizer(RosterConstraints.standard())
inj_res = opt_inj.optimize(injured_pool)

print("=== Injury Scenario ===")
print(opt_inj.analyze_lineup(inj_res))
print()
# Show excluded
excluded = [p for p in injured_pool if not p.is_available()]
print("Excluded from pool:")
for p in excluded:
    print(f"  • {p.name:25} {p.status.value}")
"""))

    cells.append(md("""\
### 4. Team Stack Limits

Some leagues limit how many players you can start from a single NFL team.
This encourages diversification and reduces reliance on one team's performance."""))
    cells.append(code("""\
# Create a pool with heavy KC/SF concentration
stack_pool = make_pool()
# Add extra KC and SF players
stack_pool.extend([
    Player("Rashee Rice", "WR", "KC", 12.5),
    Player("Isiah Pacheco", "RB", "KC", 13.8),
    Player("Brandon Aiyuk", "WR", "SF", 12.0),
    Player("Brock Purdy", "QB", "SF", 18.5),
])

# No limit baseline
opt_nolimit = LineupOptimizer(RosterConstraints.standard())
nolimit_res = opt_nolimit.optimize(stack_pool)

# Max 2 per team
limited = RosterConstraints.standard()
limited.max_players_per_team = 2
opt_limited = LineupOptimizer(limited)
limited_res = opt_limited.optimize(stack_pool)

def team_distribution(result):
    dist = {}
    for p in result.starters:
        dist[p.team] = dist.get(p.team, 0) + 1
    return dist

print("=== No Stack Limit ===")
print(opt_nolimit.analyze_lineup(nolimit_res))
print(f"Team dist: {team_distribution(nolimit_res)}")
print()

print("=== Max 2 Players/Team ===")
print(opt_limited.analyze_lineup(limited_res))
print(f"Team dist: {team_distribution(limited_res)}")
print()
print(f"Cost of constraint: {nolimit_res.total_points - limited_res.total_points:.1f} pts")
"""))

    cells.append(md("""\
### 5. Salary Cap (DFS-Style)

DraftKings-style salary cap adds a knapsack constraint. Let's use a bigger
synthetic pool and sweep the cap to see the trade-off curve."""))
    cells.append(code("""\
import warnings
from pulp import PULP_CBC_CMD, LpMaximize, LpProblem, LpVariable, lpSum, value

def make_dfs_pool(n_per_pos=None, seed=42):
    \"\"\"Synthetic DFS-style players with correlated salary & projection.\"\"\"
    rng = np.random.default_rng(seed)
    if n_per_pos is None:
        n_per_pos = {"QB": 20, "RB": 30, "WR": 45, "TE": 15, "DST": 10}

    sal_range = {"QB": (5000, 9500), "RB": (3500, 10000),
                 "WR": (3000, 9500), "TE": (2800, 7500), "DST": (2000, 4500)}
    proj_range = {"QB": (8, 28), "RB": (4, 26), "WR": (3, 24),
                  "TE": (2, 18), "DST": (2, 14)}

    rows = []
    for pos, n in n_per_pos.items():
        salaries = rng.uniform(*sal_range[pos], size=n)
        projs = rng.uniform(*proj_range[pos], size=n)
        lo, hi = sal_range[pos]
        projs += (salaries - lo) / (hi - lo) * 5  # correlation
        for i, (s, pr) in enumerate(zip(salaries, projs)):
            rows.append({
                "player": f"{pos}_{i:03d}", "position": pos,
                "team": f"T{rng.integers(1, 33):02d}",
                "salary": int(round(s / 100) * 100),
                "projected_points": round(float(pr), 2),
            })
    return pd.DataFrame(rows)

dfs_pool = make_dfs_pool()
print(f"{len(dfs_pool)} players, "
      f"salary range ${dfs_pool['salary'].min():,}-${dfs_pool['salary'].max():,}")

def solve_salary_cap(df, cap):
    prob = LpProblem("DFS_Cap_Sweep", LpMaximize)
    players = df["player"].tolist()
    proj = dict(zip(df["player"], df["projected_points"]))
    pos = dict(zip(df["player"], df["position"]))
    sal = dict(zip(df["player"], df["salary"]))
    x = {p: LpVariable(f"x_{i}", cat="Binary") for i, p in enumerate(players)}
    prob += lpSum(proj[p] * x[p] for p in players)
    prob += lpSum(sal[p] * x[p] for p in players) <= cap
    # Position constraints (DK classic: 1 QB, 2 RB, 3 WR, 1 TE, 1 FLEX, 1 DST)
    pos_req = {"QB": 1, "RB": 2, "WR": 3, "TE": 1, "DST": 1}
    flex = ["RB", "WR", "TE"]
    for position, count in pos_req.items():
        eligible = [p for p in players if pos[p] == position]
        if position in flex:
            prob += lpSum(x[p] for p in eligible) >= count
        else:
            prob += lpSum(x[p] for p in eligible) == count
    flex_elig = [p for p in players if pos[p] in flex]
    base = sum(pos_req.get(fp, 0) for fp in flex)
    prob += lpSum(x[p] for p in flex_elig) == base + 1  # +1 flex
    prob += lpSum(x[p] for p in players) == sum(pos_req.values()) + 1
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        prob.solve(PULP_CBC_CMD(msg=0))
    if prob.status != 1:
        return None, 0, 0
    starters = [p for p in players if x[p].varValue and x[p].varValue > 0.5]
    total_sal = sum(sal[p] for p in starters)
    return starters, value(prob.objective), total_sal

caps = [35000, 40000, 45000, 50000, 55000, 60000]
cap_results = []
for cap in caps:
    line, obj, used = solve_salary_cap(dfs_pool, cap)
    cap_results.append({"cap": cap, "used": used, "projected": round(obj, 1),
                        "efficiency": round(obj / used * 10000, 2) if used else 0})

df_cap = pd.DataFrame(cap_results)
print()
print("=== Salary Cap Sweep ===")
print(df_cap.to_string(index=False))

fig, ax1 = plt.subplots(figsize=(8, 5))
ax1.plot(df_cap["cap"], df_cap["projected"], "bo-", label="Projected Points")
ax1.set_xlabel("Salary Cap ($)")
ax1.set_ylabel("Projected Points", color="b")
ax1.tick_params(axis="y", labelcolor="b")

ax2 = ax1.twinx()
ax2.plot(df_cap["cap"], df_cap["efficiency"], "rs--", label="Pts / $10k")
ax2.set_ylabel("Efficiency (pts / $10k)", color="r")
ax2.tick_params(axis="y", labelcolor="r")

fig.suptitle("Salary Cap vs Projected Points & Efficiency")
fig.tight_layout()
plt.show()
"""))

    cells.append(md("""\
The efficiency curve shows diminishing returns — the highest-value players
(pts per dollar) are mid-range, but the optimizer can only take 9, so
eventually adding salary room doesn't help much.
"""))

    cells.append(md("""\
### 6. Combining Constraints

Real leagues often combine multiple rules. Let's simulate a specific league:
- Standard roster (QB, 2RB, 2WR, TE, FLEX, K, DST)
- Max 2 players per NFL team (anti-stacking)
- Locked-in: the commissioner's favorite player (just for fun)
- Locked-out: a player you're avoiding
"""))
    cells.append(code("""\
combined = RosterConstraints(
    positions={"QB": 1, "RB": 2, "WR": 2, "TE": 1, "K": 1, "DST": 1},
    flex_positions=["RB", "WR", "TE"],
    num_flex=1,
    max_players_per_team=2,
    locked_in={"Patrick Mahomes"},
    locked_out={"Raheem Mostert"},
)

opt_comb = LineupOptimizer(combined)
comb_res = opt_comb.optimize(pool)

# Compare to free
opt_free2 = LineupOptimizer(RosterConstraints.standard())
free_res2 = opt_free2.optimize(pool)

print("=== Free (no extra constraints) ===")
print(f"  Total: {free_res2.total_points:.1f}  Starters: {len(free_res2.starters)}")
print("=== Combined Constraints ===")
print(opt_comb.analyze_lineup(comb_res))
print(f"\\nCost: {free_res2.total_points - comb_res.total_points:.1f} pts")
"""))

    cells.append(md("""\
### Key Takeaways

1. **Format choice matters** — Superflex adds ~6-8 pts vs Standard by letting
   you start a 2nd QB. No-K/DST adds a skill-position slot.
2. **Locks cost points** — every constraint reduces the feasible region. The
   cost equals the difference between the constrained and unconstrained optimum.
3. **Stack limits diversify risk** — but they'll force lower-projected backups
   if your top players share a team.
4. **Salary cap creates a knapsack** — the best players aren't always the best
   values. Efficiency (pts/dollar) matters.
5. **Combined constraints interact** — the cost of multiple constraints is
   not simply additive; the solver finds the best feasible solution.
"""))

    cells.append(md(MARKDOWN_TEMPLATES["colophon"]))

    nb = nbf.v4.new_notebook(metadata=NB_METADATA)
    nb.cells = cells
    return nb


# =============================================================================
# NOTEBOOK 3 – Projection Uncertainty & Robust Lineups
# =============================================================================

def build_notebook_03() -> nbf.NotebookNode:
    cells = []

    cells.append(md("""\
# 03 — Projection Uncertainty & Robust Lineup Selection

**What you'll learn:**
- Why a single "optimal" lineup can be fragile — projections are wrong!
- How Monte Carlo simulation reveals the distribution of possible outcomes
- How to identify players who appear in optimal lineups most often ("core" players)
- How to compare ceiling vs floor across different lineup strategies
- How to build a **robust** lineup that performs well across many scenarios

**Prerequisites:** FFPy installed, `numpy`, `matplotlib`, `seaborn`. No database needed."""))
    cells.append(md(MARKDOWN_TEMPLATES["setup"]))

    cells.append(md("## Imports"))
    cells.append(code("""\
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

_repo = Path.cwd()
while not (_repo / "pyproject.toml").exists() and _repo.parent != _repo:
    _repo = _repo.parent
sys.path.insert(0, str(_repo / "src"))

from ffpy.optimizer import (
    LineupOptimizer, LineupResult,
    Player, PlayerStatus, RosterConstraints,
)

sns.set_theme(style="whitegrid")
plt.rcParams["figure.dpi"] = 120
"""))

    cells.append(md("## Data: Player Pool"))
    cells.append(code("""\
def make_pool():
    return [
        # ── QB ──
        Player("Josh Allen",       "QB", "BUF", 25.8, consistency=4.2),
        Player("Patrick Mahomes",  "QB", "KC",  24.5, consistency=3.8),
        Player("Lamar Jackson",    "QB", "BAL", 24.2, consistency=5.1),
        Player("Jalen Hurts",      "QB", "PHI", 23.1, consistency=4.5),
        Player("Joe Burrow",       "QB", "CIN", 22.0, consistency=3.5),
        Player("Dak Prescott",     "QB", "DAL", 21.5, consistency=4.0),
        # ── RB ──
        Player("Christian McCaffrey","RB", "SF", 22.4, consistency=6.0),
        Player("Saquon Barkley",   "RB", "PHI", 20.1, consistency=5.5),
        Player("Bijan Robinson",   "RB", "ATL", 19.2, consistency=5.0),
        Player("Austin Ekeler",    "RB", "WAS", 18.7, consistency=4.8),
        Player("Derrick Henry",    "RB", "BAL", 17.5, consistency=6.5),
        Player("James Cook",       "RB", "BUF", 15.2, consistency=4.0),
        # ── WR ──
        Player("Tyreek Hill",      "WR", "MIA", 19.8, consistency=5.2),
        Player("CeeDee Lamb",      "WR", "DAL", 18.5, consistency=4.5),
        Player("Justin Jefferson", "WR", "MIN", 18.2, consistency=4.0),
        Player("Amon-Ra St. Brown","WR", "DET", 16.9, consistency=3.5),
        Player("Stefon Diggs",     "WR", "HOU", 14.3, consistency=4.2),
        Player("Davante Adams",    "WR", "LV",  14.8, consistency=5.0),
        # ── TE ──
        Player("Travis Kelce",     "TE", "KC",  16.5, consistency=4.5),
        Player("Mark Andrews",     "TE", "BAL", 14.2, consistency=4.0),
        Player("George Kittle",    "TE", "SF",  13.1, consistency=5.5),
        Player("Sam LaPorta",      "TE", "DET", 12.5, consistency=3.5),
        # ── K ──
        Player("Justin Tucker",    "K",  "BAL",  9.5, consistency=2.0),
        Player("Harrison Butker",  "K",  "KC",   9.2, consistency=2.5),
        # ── DST ──
        Player("49ers DST",        "DST","SF",  10.2, consistency=3.0),
        Player("Ravens DST",       "DST","BAL",  9.5, consistency=3.5),
        Player("Cowboys DST",      "DST","DAL",  8.8, consistency=4.0),
    ]

base_pool = make_pool()
print(f"{len(base_pool)} players")
"""))

    cells.append(md("""\
### 1. Understanding Projection Variance

The `Player.consistency` attribute stores the standard deviation of recent
scores. Players with high consistency (std dev) are boom-or-bust — they might
score 30 or 8. Low-consistency players are reliable.

Let's visualise the distribution of possible outcomes:"""))
    cells.append(code("""\
rng = np.random.default_rng(42)
outcomes = 5000

# Compare a high-consistency vs low-consistency player
reliable = {"name": "Amon-Ra St. Brown", "proj": 16.9, "std": 3.5}
volatile = {"name": "Derrick Henry",     "proj": 17.5, "std": 6.5}

reliable_scores = rng.normal(reliable["proj"], reliable["std"], outcomes)
volatile_scores = rng.normal(volatile["proj"], volatile["std"], outcomes)

fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(reliable_scores, bins=60, alpha=0.6, label=f"{reliable['name']} (σ={reliable['std']})", density=True)
ax.hist(volatile_scores, bins=60, alpha=0.6, label=f"{volatile['name']} (σ={volatile['std']})", density=True)
ax.axvline(reliable["proj"], color="C0", ls="--", alpha=0.5)
ax.axvline(volatile["proj"], color="C1", ls="--", alpha=0.5)
ax.set_xlabel("Fantasy Points")
ax.set_ylabel("Density")
ax.set_title("Outcome Distribution: Reliable vs Volatile Player")
ax.legend()
plt.show()
"""))

    cells.append(md("""\
**Insight:** The volatile player has higher upside but also deeper downside.
A single "optimal" lineup ignores this — it treats `17.5` as a certainty.
"""))

    cells.append(md("""\
### 2. Monte Carlo Simulation Framework

We'll simulate the "true" outcome for each player by sampling from a normal
distribution centered on their projection with their consistency as σ.
Then we re-optimize the lineup with each simulated outcome set.

**The question:** Which players appear in the optimal lineup most often?"""))

    cells.append(code("""\
def monte_carlo_optimize(pool, n_sims=1000, seed=42):
    \"\"\"
    Run n_sims Monte Carlo simulations:
    - For each sim, draw each player's "true" score from N(proj, consistency^2)
    - Re-optimize the lineup
    - Track which players are selected
    Returns: selection_counts, avg_lineup_score, lineup_scores
    \"\"\"
    rng = np.random.default_rng(seed)
    constraints = RosterConstraints.standard()

    # Track how often each player is selected
    selection_counter = Counter()
    lineup_scores = []

    for sim in range(n_sims):
        # Create simulated player pool with perturbed projections
        sim_pool = []
        for p in pool:
            # If consistency is 0 or None, use 15% of projection as std
            std = p.consistency if (p.consistency and p.consistency > 0) else p.projected_points * 0.15
            simulated_pts = round(float(rng.normal(p.projected_points, std)), 1)
            sim_pool.append(Player(
                name=p.name,
                position=p.position,
                team=p.team,
                projected_points=max(0.1, simulated_pts),  # floor at 0.1
                consistency=p.consistency,
            ))

        try:
            opt = LineupOptimizer(constraints)
            res = opt.optimize(sim_pool)
            for starter in res.starters:
                selection_counter[starter.name] += 1
            lineup_scores.append(res.total_points)
        except ValueError:
            lineup_scores.append(0.0)  # Infeasible — shouldn't happen

    return selection_counter, lineup_scores

n_sims = 1000
counter, scores = monte_carlo_optimize(base_pool, n_sims=n_sims)
print(f"Ran {n_sims} simulations")

# Show selection frequency
selection_df = pd.DataFrame([
    {"player": name, "selection_pct": round(count / n_sims * 100, 1), "times_selected": count}
    for name, count in counter.most_common()
])
print(f"\\n=== Player Selection Frequency (top 15) ===")
print(selection_df.head(15).to_string(index=False))
"""))

    cells.append(md("""\
### 3. Visualize Selection Frequencies"""))
    cells.append(code("""\
# Add position info
pos_map = {p.name: p.position for p in base_pool}
selection_df["position"] = selection_df["player"].map(pos_map)

fig, ax = plt.subplots(figsize=(12, 6))
colors = {"QB": "#1f77b4", "RB": "#ff7f0e", "WR": "#2ca02c", "TE": "#d62728",
          "K": "#9467bd", "DST": "#8c564b"}

top20 = selection_df.head(20).sort_values("selection_pct")
ax.barh(range(len(top20)), top20["selection_pct"],
        color=[colors[p] for p in top20["position"]])
ax.set_yticks(range(len(top20)))
ax.set_yticklabels(top20["player"])
ax.set_xlabel("Selection Frequency (%)")
ax.set_title(f"Player Selection Frequency across {n_sims} Monte Carlo Simulations")
ax.legend(handles=[
    plt.Rectangle((0, 0), 1, 1, color=c, label=p)
    for p, c in colors.items()
], title="Position")
plt.tight_layout()
plt.show()

print("Players with >90% selection rate (core starters):")
core = selection_df[selection_df["selection_pct"] > 90]
if not core.empty:
    for _, row in core.iterrows():
        print(f"  • {row['player']:25} {row['position']:3}  ({row['selection_pct']:.0f}%)")
else:
    print("  (none — high uncertainty across the board)")
"""))

    cells.append(md("""\
### 4. Lineup Score Distribution

Now let's look at the distribution of total lineup scores across all simulations.
This tells us the expected range of outcomes:"""))
    cells.append(code("""\
scores_arr = np.array(scores)
scores_arr = scores_arr[scores_arr > 0]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram
axes[0].hist(scores_arr, bins=40, edgecolor="white", alpha=0.7)
axes[0].axvline(np.mean(scores_arr), color="r", ls="--", label=f"Mean: {np.mean(scores_arr):.1f}")
axes[0].axvline(np.percentile(scores_arr, 5), color="orange", ls=":", label=f"5th: {np.percentile(scores_arr, 5):.1f}")
axes[0].axvline(np.percentile(scores_arr, 95), color="orange", ls=":", label=f"95th: {np.percentile(scores_arr, 95):.1f}")
axes[0].set_xlabel("Total Projected Points")
axes[0].set_ylabel("Frequency")
axes[0].set_title("Distribution of Optimal Lineup Scores")
axes[0].legend()

# Cumulative distribution
sorted_scores = np.sort(scores_arr)
cdf = np.arange(1, len(sorted_scores) + 1) / len(sorted_scores)
axes[1].plot(sorted_scores, cdf)
axes[1].axhline(0.5, color="gray", ls="--", alpha=0.5)
axes[1].axvline(np.median(scores_arr), color="r", ls="--", label=f"Median: {np.median(scores_arr):.1f}")
axes[1].set_xlabel("Total Projected Points")
axes[1].set_ylabel("Cumulative Probability")
axes[1].set_title("CDF of Optimal Lineup Scores")
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"Score stats across {len(scores_arr)} simulations:")
print(f"  Mean:   {np.mean(scores_arr):.1f}")
print(f"  Median: {np.median(scores_arr):.1f}")
print(f"  Std:    {np.std(scores_arr):.1f}")
print(f"  5th-95th range: {np.percentile(scores_arr, 5):.1f} – {np.percentile(scores_arr, 95):.1f}")
print(f"  Min:    {scores_arr.min():.1f}")
print(f"  Max:    {scores_arr.max():.1f}")
"""))

    cells.append(md("""\
### 5. Ceiling vs Floor: Comparing Lineup Strategies

Let's compare two strategies:
1. **Point-maximizing** — the standard optimizer (maximise sum of projections)
2. **Floor-maximizing** — prefer low-consistency (reliable) players, trading
   some upside for stability

We'll implement floor-maximising by lowering the projection of high-consistency
players before optimisation:"""))
    cells.append(code("""\
def floor_optimize(pool):
    \"\"\"Penalize volatile players: adj_proj = proj - 0.5 * consistency\"\"\"
    adj_pool = []
    for p in pool:
        penalty = 0.5 * (p.consistency if p.consistency else p.projected_points * 0.15)
        adj_pool.append(Player(
            name=p.name, position=p.position, team=p.team,
            projected_points=max(0.1, p.projected_points - penalty),
            consistency=p.consistency,
        ))
    opt = LineupOptimizer(RosterConstraints.standard())
    return opt.optimize(adj_pool)

# Run both strategies
pt_opt = LineupOptimizer(RosterConstraints.standard())
max_res = pt_opt.optimize(base_pool)

floor_res = floor_optimize(base_pool)

print("=== Point-Maximising (Standard) ===")
print(pt_opt.analyze_lineup(max_res))
print()
print("=== Floor-Maximising (Consistency-Adjusted) ===")
print(pt_opt.analyze_lineup(floor_res))

# Simulate both lineups against the Monte Carlo outcomes
def simulate_lineup(lineup_players, pool, n_sims=5000):
    rng = np.random.default_rng(99)
    scores = []
    for _ in range(n_sims):
        total = 0
        for p in lineup_players:
            std = p.consistency if p.consistency and p.consistency > 0 else p.projected_points * 0.15
            total += max(0.1, rng.normal(p.projected_points, std))
        scores.append(total)
    return np.array(scores)

max_scores = simulate_lineup(max_res.starters, base_pool)
floor_scores = simulate_lineup(floor_res.starters, base_pool)

fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(max_scores, bins=50, alpha=0.5, label="Point-Maximising", density=True)
ax.hist(floor_scores, bins=50, alpha=0.5, label="Floor-Maximising", density=True)
ax.axvline(np.mean(max_scores), color="C0", ls="--")
ax.axvline(np.mean(floor_scores), color="C1", ls="--")
ax.set_xlabel("Total Fantasy Points")
ax.set_ylabel("Density")
ax.set_title("Simulated Outcome Distribution: Two Strategies")
ax.legend()
plt.show()

print()
print(f"{'Metric':<20} {'Point-Max':>10} {'Floor-Max':>10}")
print("-" * 42)
print(f"{'Mean':<20} {np.mean(max_scores):>10.1f} {np.mean(floor_scores):>10.1f}")
print(f"{'Std Dev':<20} {np.std(max_scores):>10.1f} {np.std(floor_scores):>10.1f}")
print(f"{'5th %ile':<20} {np.percentile(max_scores, 5):>10.1f} {np.percentile(floor_scores, 5):>10.1f}")
print(f"{'95th %ile':<20} {np.percentile(max_scores, 95):>10.1f} {np.percentile(floor_scores, 95):>10.1f}")
print(f"{'Floor risk (5th)':<20} {np.percentile(max_scores, 5):>10.1f} {np.percentile(floor_scores, 5):>10.1f}")
"""))

    cells.append(md("""\
**What to look for:**
- The point-max lineup has a higher *mean* but also a heavier left tail (worse floor)
- The floor-max lineup has a narrower distribution (less variance)
- In a winner-take-all contest, ceiling matters more. In a weekly head-to-head
  league, floor matters more.
"""))

    cells.append(md("""\
### 6. Robust Lineup Construction

A "robust" lineup is one that performs well *consistently* across many possible
outcome scenarios. The players selected most often in the Monte Carlo simulation
are the most robust — they're optimal under many different projection realizations.

Let's build a robust lineup from the top-9 most-frequently-selected players:"""))
    cells.append(code("""\
# Get the most-frequently selected players, respecting position constraints
def build_robust_lineup(selection_df, pool):
    \"\"\"Build lineup respecting position constraints from selection frequency.\"\"\"
    pos_map = {p.name: p.position for p in pool}
    proj_map = {p.name: p.projected_points for p in pool}

    # Sort by selection frequency
    sorted_players = selection_df.sort_values("selection_pct", ascending=False)
    sorted_players["position"] = sorted_players["player"].map(pos_map)

    constraints = RosterConstraints.standard()
    pos_counts = {}
    starters = []

    for _, row in sorted_players.iterrows():
        pos = row["position"]
        max_at_pos = constraints.positions.get(pos, 0)
        current_at_pos = pos_counts.get(pos, 0)

        # Check if position slot available
        if current_at_pos < max_at_pos:
            starters.append(row["player"])
            pos_counts[pos] = current_at_pos + 1

        # Check FLEX
        elif pos in constraints.flex_positions and pos_counts.get("FLEX", 0) < constraints.num_flex:
            # Count how many are already in flex-eligible positions beyond base
            flex_positions = constraints.flex_positions
            base_total = sum(constraints.positions.get(p, 0) for p in flex_positions)
            flex_used = sum(pos_counts.get(p, 0) for p in flex_positions) - base_total
            if flex_used < constraints.num_flex:
                starters.append(row["player"])
                pos_counts[pos] = current_at_pos + 1

        if len(starters) >= constraints.total_starters:
            break

    # Return Player objects
    name_map = {p.name: p for p in pool}
    return [name_map[name] for name in starters]

robust_starters = build_robust_lineup(selection_df, base_pool)
robust_total = sum(p.projected_points for p in robust_starters)
robust_vs_pointmax = max_res.total_points - robust_total

print("=== Robust Lineup (most-selected players) ===")
for p in robust_starters:
    pct = counter.get(p.name, 0) / n_sims * 100
    print(f"  {p.name:25} {p.position:3} {p.team:4}  {p.projected_points:5.1f}  (selected {pct:.0f}%)")
print(f"  {'─'*55}")
print(f"  {'Total':>25}        {robust_total:5.1f}")
print()
print(f"Point-max total:       {max_res.total_points:.1f}")
print(f"Robust total:          {robust_total:.1f}")
print(f"Cost of robustness:    {robust_vs_pointmax:+.1f} pts")
print()
print("The robust lineup trades a few points of expected value for")
print("higher confidence that the lineup will perform well in practice.")
"""))

    cells.append(md("""\
### 7. Your Turn: Sensitivity to Projections

Try changing a player's projection and re-running the Monte Carlo simulation.
How much does the optimal lineup change?"""))
    cells.append(code("""\
def sensitivity_test(player_name, new_projection, pool, n_sims=500):
    \"\"\"Test how changing one player's projection affects selection frequencies.\"\"\"
    modified_pool = []
    for p in pool:
        if p.name == player_name:
            modified_pool.append(Player(
                p.name, p.position, p.team, new_projection, consistency=p.consistency,
            ))
        else:
            modified_pool.append(p)

    counter_mod, _ = monte_carlo_optimize(modified_pool, n_sims=n_sims, seed=42)
    return counter_mod

# Example: What if Christian McCaffrey is projected for 28 pts instead of 22.4?
cmc_boosted = sensitivity_test("Christian McCaffrey", 28.0, base_pool)
cmc_pct = cmc_boosted.get("Christian McCaffrey", 0) / 500 * 100

original_pct = counter.get("Christian McCaffrey", 0) / n_sims * 100
print(f"CMC at 22.4 pts: selected in {original_pct:.0f}% of lineups")
print(f"CMC at 28.0 pts: selected in {cmc_pct:.0f}% of lineups")
print()

# See who drops when CMC rises
players_dropped = {}
for name, count in counter.items():
    new_count = cmc_boosted.get(name, 0)
    players_dropped[name] = (count / n_sims * 100) - (new_count / 500 * 100)

dropped_sorted = sorted(players_dropped.items(), key=lambda x: x[1])
print("Players whose selection rate dropped most when CMC's projection rose:")
for name, delta in dropped_sorted[:5]:
    print(f"  {name:25} {delta:+.1f}%")
"""))

    cells.append(md("""\
### Key Takeaways

1. **Projections are not certainties** — every projection has uncertainty.
   The `consistency` (std dev) captures this.
2. **Monte Carlo simulation reveals robustness** — players selected in >90% of
   simulated lineups are "core" starters.
3. **Point-maximising ≠ best strategy** — depending on your league format
   (head-to-head vs total points), you may prefer a higher floor or higher ceiling.
4. **The robust lineup option** trades expected points for reduced variance —
   useful in weekly head-to-head leagues where consistency beats boom-or-bust.
5. **Sensitivity analysis** shows how lineup construction depends on your
   projections — a small change in one player's projection can reshape the
   entire optimal lineup.
"""))

    cells.append(md(MARKDOWN_TEMPLATES["colophon"]))

    nb = nbf.v4.new_notebook(metadata=NB_METADATA)
    nb.cells = cells
    return nb


# =============================================================================
# Main
# =============================================================================

def main():
    OUT.mkdir(parents=True, exist_ok=True)

    notebooks = [
        ("01_scoring_systems_impact.ipynb", build_notebook_01),
        ("02_optimizer_constraints.ipynb", build_notebook_02),
        ("03_projection_uncertainty.ipynb", build_notebook_03),
    ]

    for filename, builder in notebooks:
        path = OUT / filename
        nb = builder()
        with open(path, "w") as f:
            nbf.write(nb, f)
        print(f"  ✓ {path.name}")

    print(f"\nDone — {len(notebooks)} notebooks written to {OUT}/")


if __name__ == "__main__":
    main()
